Add assigned column
kuunamaka/Phoenix_4 pull request #1
Opened 2020-10-03 06:23 UTC by kuunamaka

![スクリーンショット 2020-10-03 13 44 23](https://user-images.githubusercontent.com/60667652/94984895-18871b80-058c-11eb-85f2-19e678f89726.png)

もともとtodo機能のみだったものに、Userを追加/変更/削除機能をつけました。
スクリーンショットの表内に "Assigned by" の欄を作成し、そこには誰がassignしたのかわかるようにuserを表示させました。

2020-10-03 06:35 UTC, kuunamaka commented
![スクリーンショット 2020-10-03 15 33 41](https://user-images.githubusercontent.com/60667652/94985057-ea0a4000-058d-11eb-97cd-8c79bcb907d8.png)

"See all the users" をクリックした場合に表示されるUserの一覧画面です。

2020-10-03 08:01 UTC, YotaroSeki requested changes

2020-10-03 08:01 UTC, YotaroSeki commented on test/todo_tutorial/todo_test.exs
> +        end
`Enum.map(Todo.list_alphabetical_assigned(), & &1.name)`
できればforを使わないでEnumの関数などで書けるとgoodです！

2020-10-03 08:01 UTC, YotaroSeki commented on test/todo_tutorial_web/controllers/task_controller_test.exs
> +  def fixture(:task) do
defp

2020-10-03 09:18 UTC, kuunamaka commented on lib/todo_tutorial/accounts.ex
> +  def get_user(id) do
１行にすると長くなってしまいそうな関数も、１行にまとめたほうが良いでしょうか？

2020-10-03 09:18 UTC, kuunamaka commented on lib/todo_tutorial/todo/assign.ex
> +defmodule TodoTutorial.Todo.Assign do
Assigneeで統一しました！

2020-10-03 09:19 UTC, kuunamaka commented on lib/todo_tutorial/todo.ex
> +defmodule TodoTutorial.Todo do
Todosに統一させました！ありがとうございます！

2020-10-03 09:23 UTC, kuunamaka commented on lib/todo_tutorial/accounts.ex
> +  # Finding the user with their id
初めからあったものを除いてコメント修正しました！リンクもありがとうございます！

2020-10-03 09:31 UTC, kuunamaka commented on priv/repo/migrations/20200927014834_create_assigned.exs
> +defmodule TodoTutorial.Repo.Migrations.CreateAssigned do
作成時、taskの中のものだと考えていたので別で作成していましたが、assignedとusersは同じだと思います、、

調節してみて、削除できれば消します。

2020-10-03 09:40 UTC, kuunamaka commented on lib/todo_tutorial/todo/assign.ex
> +
assignedとtasksは一対多の関係になるから足した方が良い、ということでしょうか？

2020-10-03 09:44 UTC, kuunamaka commented on priv/repo/migrations/20200920111256_create_users.exs
> +      add :username, :string, null: false
「ユーザーの名前」と「id」みたいなイメージで作成しましたが、見栄えだけで足した感じです、、。
特に必要ではないと思います。💧

2020-10-09 05:49 UTC, MasashiYokota commented on lib/todo_tutorial/accounts.ex
> +  def change_user(%User{} = user), do: User.changeset(user, %{})
publicな関数は、テストと`@doc` と`@spec` はちゃんと書きましょう！

2020-10-09 05:50 UTC, MasashiYokota commented on lib/todo_tutorial/accounts/user.ex
> +  end
ここも、schemaのtypeを書くと良いです。

2020-10-09 05:51 UTC, MasashiYokota commented on lib/todo_tutorial/application.ex
> +    Supervisor.start_link(children, opts)
[質問]
ここは、phoenixで重要な関数の一つですが、具体的に何をやっている関数でしょうか？何をやっているのか調べて回答お願いします！

2020-10-09 05:53 UTC, MasashiYokota commented on lib/todo_tutorial/todo/task.ex
> +    belongs_to :assign, TodoTutorial.Todos.Assignee
ここって結局、`user`と紐付けるんじゃなかったでしたっけ？

2020-10-09 05:55 UTC, MasashiYokota commented on lib/todo_tutorial_web/router.ex
> +  end
[質問]
1. この`pipeline`は、どういうものですか？
2. `:browser`と`:api`はそれぞれ、何をするpipelineですか？

2020-10-09 05:56 UTC, MasashiYokota commented
全体に対するコメントとして、パブリックな関数は`@doc`と

2020-10-15 13:35 UTC, kuunamaka commented on lib/todo_tutorial/application.ex
> +    Supervisor.start_link(children, opts)
ここは、supervisorライブラリの関数で、child specification treeを使用してchild processの監視を行っています。9-20行目のchild specificationにてmodulesがリストで定義されており、レポジトリがcrashした際にどの順序でstart, shutdown, restartさせるかわかるようになっています。
監視する事で、必要な場合のみ再起動などを行う事ができるため、全体の堅牢性を確保する事ができます！

（`start_link/2` の1つ目のargumentでは上のchild specificationのリスト、2つ目にはoptionのキーワードリストで失敗したchildプロセスのみを再起動する役割を持つ`:one_for_one` とsupervisorプロセスに対してregisterしているmodule nameが入れられています。）

2020-10-16 11:23 UTC, kuunamaka commented on lib/todo_tutorial_web/router.ex
> +  end
1. `plug` の順序を説明しているもので、リクエストに関する処理を定義しているものだと思います。
2. `:browser` はブラウザのリクエストのパイプラインで
　・`"html"` を受け入れる、リクエストフォーマット
　・セッションのデータ取得、接続
　・フラッシュメッセージの取得
　・下2つはweb app内のの脆弱性を利用した攻撃対策
　を行っており、
　`:api` は`"json"` を受け入れるパイプラインです！

2020-11-20 05:22 UTC, merged