Add favorite to the task
kuunamaka/Phoenix_4 pull request #2
Opened 2020-11-13 08:27 UTC by kuunamaka

taskに対していいね機能をつけました。

2020-11-13 09:27 UTC, MasashiYokota requested changes
ざっくりとコメントしました！

2020-11-13 09:27 UTC, MasashiYokota commented on lib/todo_tutorial/todo.ex
> +  end
private functionに吐き出したところは良いのですが、単に
```suggestion
  defp alphabetical(query) do
     order_by(query, asc: :name) 
  end
```
とかのほうがスッキリして良いですね。あと、関数名はalphabeticalじゃなくて、nameにorderを加えているのでその要素を関数名に含めるとよりわかりやすくなると思います。
関数名も考え直してみましょう！

2020-11-13 09:27 UTC, MasashiYokota commented on lib/todo_tutorial/todo.ex
> +    Repo.insert(%FavoritedTask{task_id: task.id, user_id: user.id})
changesetに噛ませたほうが良いですね。

2020-11-20 05:52 UTC, poly65536 commented on lib/todo_tutorial/todo/task.ex
> +    many_to_many :users, TodoTutorial.Accounts.User, join_through: "favorited_tasks"
どういうユーザーかわかりにくい（作った人、アサインされた人等）ので、`favorited_users`等の方がわかりやすくなると思います。

2020-11-20 05:52 UTC, poly65536 commented on lib/todo_tutorial/todo/task.ex
> +    belongs_to :assign, TodoTutorial.Accounts.User
`assignee`や`assigned_user`のほうがユーザー感が出て良いです。

2020-11-20 11:43 UTC, poly65536 commented on lib/todo_tutorial_web/templates/task/index.html.eex
> +          <%= if Enum.member?(task.favorited_users, @user) do %>
`did_favorite?`みたいな関数を作ったほうが、どういう条件でボタンが切り替わるかわかりやすくなると思います。あと、viewからはできるだけロジックを切り離したほうがきれいになります。

2020-11-20 11:43 UTC, poly65536 commented on lib/todo_tutorial_web/controllers/task/task_controller.ex
> +        render(conn, "new.html", changeset: changeset)
エラーが起きたときは、`put_flash`でエラーメッセージを表示すると良いです！

2020-11-20 11:43 UTC, poly65536 commented on lib/todo_tutorial_web/views/user_view.ex
> +    hd([name])
このコードでファーストネーム取れますか・・・？

2020-11-20 11:43 UTC, poly65536 commented on priv/repo/migrations/20200927015812_add_assign_id_to_task.exs
> +      add :assign_id, references(:users)
可能ならカラム名も直してください！

2020-11-27 03:52 UTC, MasashiYokota commented on lib/todo_tutorial/accounts.ex
> +  def get_user_by_id(params), do: Repo.get_by(User, params)
`get_user_by_id`という名前なので、渡すのはマップじゃなくて、直接IDを渡すようにしたほうがわかりやすいです！

2020-11-27 03:52 UTC, MasashiYokota commented on lib/todo_tutorial/accounts.ex
> +  def get_user_by_name(params), do: Repo.get_by(User, params)
これも同様です。

2020-11-27 03:53 UTC, MasashiYokota commented on lib/todo_tutorial/accounts.ex
> +  end
preloadってN+1 Query問題を解決するためにやることが多いんですけど、
このN+1 Query問題を調べて、返信お願いします！

2020-11-27 03:59 UTC, MasashiYokota commented on node_modules/milligram/changelog.md
> +# Changelog
なぜか、`node_modules`がコミットに入っていますね。
プロジェクトのルートにあるnode_moduleを使っていないなら消してください！

2020-11-27 04:56 UTC, kuunamaka commented on lib/todo_tutorial/accounts.ex
> +  end
N+1 Query問題とは、ループ処理を行う際に、
SQLのクエリを「N(データ量)+1」回発行している状態を示し、取得データ量(N)が多くなるほどパフォーマンスが悪くなることです。

他のテーブル情報を先に読み込むために、preloadを使用すれば、
指定したテーブルごとに取得するクエリを分け、キャッシュするので
N+1 Query問題を解決することが可能なんだと思います。

2020-11-27 05:00 UTC, MasashiYokota commented
ｌｇｔｍ

2020-11-27 05:09 UTC, merged