Add vue.js view
kuunamaka/Phoenix_4 pull request #4
Opened 2020-12-25 05:16 UTC by kuunamaka

2021-01-29 06:59 UTC, MasashiYokota commented on assets/js/src/components/add_task.vue
> +      }
console.logはデバッグコードなので、全部消しましょう。他ファイルも同じです。

2021-01-29 07:00 UTC, MasashiYokota commented on assets/js/src/components/add_user.vue
> +        console.log(resp);
respに代入する必要ないですね。

2021-01-29 07:00 UTC, MasashiYokota commented on assets/js/src/components/delete_task.vue
> +        window.location.href = '/tasks';
ここも。

2021-01-29 07:00 UTC, MasashiYokota commented on assets/js/src/components/delete_user.vue
> +        console.log(resp);
ここも。

2021-01-29 07:00 UTC, MasashiYokota commented on assets/js/src/components/edit_task.vue
> +        console.log(resp);
ここも！

2021-01-29 07:01 UTC, MasashiYokota commented on assets/js/src/components/edit_task.vue
> +        console.log(resp);
他ファイルも同様です。

2021-01-29 07:20 UTC, MasashiYokota commented on assets/js/src/components/add_task.vue
> +      }
errorハンドリングしていないので、try...catch不要です。他も同様です

2021-01-29 07:21 UTC, MasashiYokota commented on assets/js/src/components/add_task.vue
> +      }
あ、フォーム上等でエラーメッセージを表示するように修正して下さい。

2021-02-01 04:04 UTC, shunjilin requested changes
just some minor comments!

Not sure if you are using a formatter but you may want to set up auto formatting in your editor when you save your files

2021-02-01 04:04 UTC, shunjilin commented on assets/test/components/add_user.spec.js
> +      expect(wrapper.element).toMatchSnapshot();
This is perfectly fine, but for bigger components, you may only want to use snapshot tests to make sure the overall component is rendered correctly, but for testing individual responsibilities, e.g. if the correct error is rendered for the post request, snapshots may be hard to maintain as the test breaks when functionality not related to the specific test changes. For example if I change the text of the button, even though that is unrelated to this test, this test's snapshot will become outdated

You may want to investigate vue test util's `find` https://vue-test-utils.vuejs.org/api/wrapper/find.html#find or `get` https://vue-test-utils.vuejs.org/api/wrapper/#get functions to retrieve the specific tag element and check the error message.

2021-02-01 04:27 UTC, kuunamaka commented on assets/js/src/components/task_list.vue
> +      await axios.delete(`/api/tasks` + `/${ task.id }` + `/users` + `/1`, {
The reason why I put 1 instead of user_id is that I'm only allowing one user to like the task since I haven't created any login/ out sessions.

2021-02-01 06:53 UTC, merged